### PR TITLE
Added torus knot

### PR DESCRIPTION
**Pull request by 01000001-01101011**
I added an additional alias in the frame map, I hope that's not a problem?

### CODE REVIEW

**Comment by 01000001-01101011** [comment]
@hugomd do you still exist?

**Comment by 01000001-01101011** [comment]
@hugomd evidently you do :P

image

**Comment by hugomd** [comment]
@01000001-01101011 I exist, but I don't have much time to maintain open source projects outside of work and life 🙃 

I've merged your changes in and will deploy shortly ✌🏻

**Comment by 01000001-01101011** [comment]
Awesome, thank you very much!

**Pull request closed without merging**
